### ISSUE TITLE
MAJOR UPDATE FIXES 

### ISSUE THREAD

**Issue by gradedSystem** [datasets/country-codes#81]
## Description
The `country-codes` dataset is currently outdated and not supported, there is urgent need of fixing the whole codebase of the datasets and making sure it runs on the daily bases.

## Acceptance criteria
- [x] Fix the structure of the codebase
- [x] Remove unnecessary scripts or files that are outdated
- [x] Run GitHub Actions on monthly bases

## Tasks
- [x] Fix the `/scripts` folder
- [x] Remove `travis.yml` file 
- [x] Update `Makefile`
- [x] Update `README.md`
- [x] Run Github Actions cron job
- [x] Update the links everywhere
- [x] Update `requirements.txt` file
- [x] Fix down the most recent issues and remove unnecessary ones(rest of them which are outdated)
  - [x] #80 
 

> Note: Since changing the whole codebase and structure is ongoing current pull request should be irrelevant

**Comment by gradedSystem** [comment]
This is fixed
